trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python38Linux:
        imageName: 'ubuntu-18.04'
        python.version: '3.8'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: "Uninstall all packages"

  - script: pip install dist/*.tar.gz
    displayName: 'Install from sdist'

  - script: |
      pip install -r requirements.txt
      python -m pytest --pyargs spacy_legacy
    displayName: 'Run tests'
